info:
  name: AdminTools
  author: SanyaPilot
  version: 1.0.2
  src_url: https://github.com/PBModular/AdminTools
  description: Some essential commands for group chat administration

permissions:
  - require_db

config:
  warn_defaults:
    limit: 5
    restriction: "kick"  # One of ban, mute, kick
    time: 0  # Time in seconds for timed restriction (e. g. ban or mute). Value < 30 is considered as infinity
